# https://rust-lang.github.io/rustfmt/

array_width = 100
condense_wildcard_suffixes = true
edition = "2021"
fn_params_layout = "Vertical"
force_multiline_blocks = true
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_layout = "HorizontalVertical"
newline_style = "Unix"
reorder_impl_items = true
spaces_around_ranges = true
struct_lit_single_line = false
unstable_features = true
use_field_init_shorthand = true
wrap_comments = true